server:
  port: 8087

spring:
  application:
    name: Notification Service
    group: com.movie-netscape
    version: 1.0.0

  mail:
    host: smtp.gmail.com
    port: 465
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
        debug: true